import type { Point } from '../../src/types';

export const POINTS: Point[] = [
    {
        name: 'Prototyp zakopu',
        description: 'Prozkoumejte prototyp pechotniho zakopu. Nachazi se v oblasti latrin na zakladne Stare Hute',
        geo: '49.1399306N, 17.2896453E',
        code: '',
        resolved: false,
    },
    {
        name: 'Sklipek na brambory',
        description: 'Za potokem na Hutich smerem na hladnou vodu je sklipek na brambory.',
        geo: '49.1396081N, 17.2860458E',
        code: '',
        resolved: false,
    },
    {
        name: 'Malikova lipa',
        description: 'Lipa nachazejici se na brehu potoka Kyjovky na severnim okraji obce Stare Hute',
        geo: '49.1392008N, 17.2869528E',
        code: '',
        resolved: false,
    },
    {
        name: 'Vysilac Vlcak',
        description: 'Za vysilacem',
        geo: '49.1603731N, 17.2786983E',
        code: '',
        resolved: false,
    },
    {
        name: 'Kaple svateho Jana Nepomuckeho',
        description: 'Kaple svateho Jana Nepomuckeho na Salasi. Z boku na hrbitovni zdi',
        geo: '49.1389342N, 17.3428675E',
        code: '',
        resolved: false,
    },
    {
        name: 'Altanek Buchlov Sutr',
        description: 'Buchlovsky Kamen, altanek na louce.',
        geo: '49.1360706N, 17.2999897E',
        code: '',
        resolved: false,
    },
    {
        name: 'Hajovna na Hladne vode',
        description: 'Ze zadu za hajovnou',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: 'dds',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        geo: '49.1445072N, 17.2869114E',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        code: '',
        resolved: false,
    },
    {
        name: '',
        description: '',
        code: '',
        resolved: false,
    },
]
